ompl/ompl

- src/ompl/base/SpaceInformation.h
- src/ompl/geometric/planners/rrt/RRTstar.h
- src/ompl/util/RandomNumbers.h
- src/ompl/util/src/RandomNumbers.cpp
The changes discussed in #46 as a single commit.
> Cleaned pull requests

- src/ompl/base/MotionValidator.h
- src/ompl/base/OptimizationObjective.h
- src/ompl/base/Path.h
- src/ompl/base/PlannerTerminationCondition.h
- src/ompl/base/ProblemDefinition.h
- src/ompl/base/SpaceInformation.h
- src/ompl/base/src/OptimizationObjective.cpp
- src/ompl/base/src/PlannerTerminationCondition.cpp
Hi Guys,
So I found a few more miscellaneous features when getting the Informed Sampling pull request ready. I figured it was better to do them separately first and keep things a little more neat and tidy.
So here you go!
Jon
> More miscellanea

- src/ompl/geometric/planners/experience/src/LightningRetrieveRepair.cpp
- src/ompl/tools/experience/ExperienceSetup.h
- src/ompl/tools/lightning/src/Lightning.cpp
Reduced various warnings to just ``INFORM`` because they are intended functionality
Added new virtual function ``doPostProcessing()`` to ``ExperienceSetup`` that allows an experience planner (Thunder) to process a new trajectory into its database in an asynchronous manner. 
In preparation for Thunder PR
> Lightning updates

- demos/OptimalPlanning.cpp
- demos/OptimalPlanning.py
- src/ompl/base/OptimizationObjective.h
- src/ompl/base/PlannerTerminationCondition.h
- src/ompl/base/objectives/src/PathLengthOptimizationObjective.cpp
- src/ompl/base/samplers/informed/PathLengthDirectInfSampler.h
- src/ompl/base/src/PlannerTerminationCondition.cpp
- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
- src/ompl/geometric/planners/cforest/CForest.h
- src/ompl/geometric/planners/cforest/src/CForest.cpp
- src/ompl/geometric/planners/rrt/InformedRRTstar.h
- src/ompl/geometric/planners/rrt/RRTstar.h
- src/ompl/geometric/planners/rrt/src/InformedRRTstar.cpp
- src/ompl/geometric/planners/rrt/src/RRTstar.cpp
- src/ompl/util/ProlateHyperspheroid.h
- src/ompl/util/RandomNumbers.h
Ok,
So here is the changes to use informed sampling in RRT\* (i.e., Informed RRT\*). While I was at it, I cleaned a thing or two up in the RRT\* code, so I'll be going through to put some inline comments about those as well.
I'm working to "relax" informed sampling to handle multiple starts/goals (i.e., GOAL_STATE**S**), so I'll submit that after this PR, hopefully before the next release.
> Informed RRT*

- .gitignore
- demos/CMakeLists.txt
- demos/Diagonal.cpp
- py-bindings/headers_geometric.txt
- src/ompl/datastructures/BinaryHeap.h
- src/ompl/geometric/planners/rrt/RRTX.h
- src/ompl/geometric/planners/rrt/RRTsharp.h
- src/ompl/geometric/planners/rrt/src/RRTX.cpp
- src/ompl/geometric/planners/rrt/src/RRTsharp.cpp
- src/ompl/geometric/planners/rrt/src/RRTstar.cpp
- Implementation of RRT# and RRTX
- Adding check of max range in RRT* when using k-nearest neighbors
> Implementation of RRT# and RRTX

- .travis.yml
- scripts/docker/debian-jessie
- scripts/docker/ubuntu-xenial
* Add Dockerfiles for Ubuntu Xenial and Debian Jessie
* Test in Docker via Travis
* Disable Travis cache of /usr/local under linux due to timeouts
> Dockerized Travis build

- src/ompl/base/StateSpace.h
- src/ompl/base/src/Planner.cpp
Also default console print value
> Better debug output for invalid goal states

- demos/RigidBodyPlanningWithControls.cpp
Comment says one second, but the args are 10 .
> fixed comment about solve() seconds.

- src/ompl/geometric/planners/rrt/RRTstar.h
- src/ompl/geometric/planners/rrt/src/RRTstar.cpp
https://bitbucket.org/ompl/ompl/issues/373/informedrrtstar-segfault
> Fix for Issue #373 on BitBucket.

- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/datastructures/CostHelper.h
- src/ompl/geometric/planners/bitstar/datastructures/ImplicitGraph.h
- src/ompl/geometric/planners/bitstar/datastructures/SearchQueue.h
- src/ompl/geometric/planners/bitstar/datastructures/Vertex.h
- src/ompl/geometric/planners/bitstar/datastructures/src/ImplicitGraph.cpp
- src/ompl/geometric/planners/bitstar/datastructures/src/SearchQueue.cpp
- src/ompl/geometric/planners/bitstar/datastructures/src/Vertex.cpp
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
Remove shared_ptr cycle in BITstar by using raw pointers.
> Fix Issue #380

- src/ompl/base/spaces/src/SO3StateSpace.cpp
Fix broken link to Matt Mason's lecture notes on quaternions.
> Fix broken link

- install-ompl-ubuntu.sh.in
'set -e' added to the beginning of the script to ensure that script will stop execution in case it fails midway.
> Install script update

- src/ompl/geometric/planners/informedtrees/AITstar.h
- src/ompl/geometric/planners/informedtrees/aitstar/Edge.h
- src/ompl/geometric/planners/informedtrees/aitstar/ImplicitGraph.h
- src/ompl/geometric/planners/informedtrees/aitstar/Queuetypes.h
- src/ompl/geometric/planners/informedtrees/aitstar/Vertex.h
- src/ompl/geometric/planners/informedtrees/aitstar/src/Edge.cpp
- src/ompl/geometric/planners/informedtrees/aitstar/src/ImplicitGraph.cpp
- src/ompl/geometric/planners/informedtrees/aitstar/src/Vertex.cpp
- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
This PR refactors AIT* and implements a slight improvement regarding the stopping condition of AIT*'s reverse search. The forward search and the resulting solutions are equivalent to before but may be discovered slightly faster.
> Refactor AIT*

- src/ompl/tools/multiplan/src/ParallelPlan.cpp
Solves #856 and https://github.com/ros-planning/moveit/issues/3003
Exceptions should be contained within thread boundaries, they cannot be caught otherwise
> Catch exceptions in worker threads in ParallelPlan

- src/ompl/tools/lightning/src/Lightning.cpp
- src/ompl/tools/thunder/src/Thunder.cpp
These are some minor changes needed to make Lightning and Thunder work with MoveIt and [Robowflex](https://kavrakilab.github.io/robowflex/), Some changes are also required from the Move-It side, I will probably make a PR there soon.
> Small fixes to make lightning and thunder work with MoveIt and robowflex

- demos/PlanarManipulator/PlanarManipulator.h
- demos/PlanarManipulator/PlanarManipulatorIKGoal.h
- demos/PlanarManipulator/PlanarManipulatorPolyWorld.h
- demos/PlanarManipulator/PlanarManipulatorStateValidityChecker.h
- demos/PlanarManipulator/PlanarManipulatorXXLDecomposition.h
This is a minor fix that makes inclusion of Eigen headers more consistent across the code base.
> Fix #include for Eigen headers in demos

- src/ompl/geometric/planners/informedtrees/ABITstar.h
> Fix link to submission video in ABIT* documentation

- demos/RigidBodyPlanningWithIntegrationAndControls.cpp
Propagator in demo is incorrect.
> Update propagater of RigidBodyPlanningWithIntegrationAndControls.cpp

- src/ompl/datastructures/NearestNeighborsGNAT.h
- src/ompl/datastructures/NearestNeighborsGNATNoThreadSafety.h
> Fix tree rebalancing bug in GNAT data structures

- src/ompl/base/PlannerDataStorage.h
- src/ompl/base/src/PlannerDataStorage.cpp
- src/ompl/control/PlannerDataStorage.h
- src/ompl/control/src/PlannerDataStorage.cpp
> Return flag to indicate PlannerData load/store success/failure

- src/ompl/geometric/src/PathGeometric.cpp
> Check if SpaceInformation is setup before checkAndRepair

- CMakeModules/FindPython.cmake
> Fix Python versions <= 3.7 finding module path

- src/ompl/geometric/planners/informedtrees/aitstar/src/ImplicitGraph.cpp
@marlinstrub This is a quick fix for #997.
This solution is similar to the one added to EIT* in #994. I could not think of a better way to fix it, so any suggestions are welcome as well.
> Fix adding invalid states to AIT* graph

- py-bindings/generate_bindings.py
- py-bindings/ompl_py_geometric.h
- src/ompl/geometric/planners/prm/ConnectionStrategy.h
See #1054. Adds KBoundedStrategy to the Python bindings.
> Added KBoundedStrategy to Python bindings

- src/ompl/geometric/planners/prm/src/PRM.cpp
> Fix Bug in Loading Planner Data

- src/ompl/base/spaces/DubinsStateSpace.h
- src/ompl/base/spaces/src/DubinsStateSpace.cpp
> remove unused parameter in getDubinsClass

- .dockerignore
- scripts/docker/ompl.Dockerfile
> Add missing build command in dockerfile

- src/ompl/geometric/planners/AnytimePathShortening.cpp
In AnytimePathShortening do not retry when the error is INVALID_START, INVALID_GOAL, or UNRECOGNIZED_GOAL_TYPE.
> Do not retry on invalid start/goal/unrecognized goal type

- .github/workflows/wheels.yaml
Applies https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
> fix(CI): upload-artifact@v4 breaking change

- .github/workflows/before_build.sh
See https://github.com/boostorg/boost/issues/924
> Fix boost download URL for wheels generation

- .github/workflows/before_all.sh
- .github/workflows/before_build.sh
- .github/workflows/build.yml
- .github/workflows/wheels.yaml
- py-bindings/pyproject.toml
This pull request includes several important changes to the build and workflow configurations, primarily to support additional architectures and update dependencies. The key changes include updates to the `before_all.sh` script, modifications to the workflow files to include new OS and architecture combinations, and updates to dependency versions.
* [`.github/workflows/before_all.sh`](diffhunk://#diff-c6c7a69c247c200922cc31e883beb718d07e751c0408b3631fb9343ac7313e12R6-R59): Added architecture-specific fixes and dependencies for AArch64, including setting up GCC and ensuring the availability of Boost-Python and PyPy.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L15-R23): Updated the matrix strategy to include new OS and …
> ARM Builds

- .github/workflows/wheels.yaml
https://github.com/pypa/cibuildwheel/releases
https://github.com/ncipollo/release-action/releases/tag/v1.16.0
https://github.com/pypa/gh-action-pypi-publish/releases?page=1
> Update libs into wheels.yaml

- src/ompl/control/planners/est/src/EST.cpp
- src/ompl/control/planners/pdst/src/PDST.cpp
- src/ompl/control/planners/rrt/src/RRT.cpp
- src/ompl/control/planners/sst/src/SST.cpp
- src/ompl/geometric/planners/kpiece/src/KPIECE1.cpp
- src/ompl/geometric/planners/pdst/src/PDST.cpp
- src/ompl/geometric/planners/rlrt/src/RLRT.cpp
- src/ompl/geometric/planners/rrt/src/LBTRRT.cpp
- src/ompl/geometric/planners/rrt/src/LazyRRT.cpp
- src/ompl/geometric/planners/rrt/src/RRT.cpp
- src/ompl/geometric/planners/rrt/src/RRTXstatic.cpp
- src/ompl/geometric/planners/rrt/src/RRTstar.cpp
- src/ompl/geometric/planners/rrt/src/TRRT.cpp
- src/ompl/geometric/planners/rrt/src/TSRRT.cpp
- src/ompl/geometric/planners/rrt/src/VFRRT.cpp
- src/ompl/geometric/planners/sst/src/SST.cpp
- src/ompl/geometric/planners/stride/src/STRIDE.cpp
Rebase and cherry pick of #1163
> Cherry pick of reverts to add back capability of tree planners to go towards non-sampleable goals

- demos/CMakeLists.txt
some demos were missing from installation
> install all demos

- doc/markdown/developers.md
> update list of contributors

- CMakeModules/FindPython.cmake
- CMakeModules/OMPLUtils.cmake
- scripts/CMakeLists.txt
0002-Added-FLANN_LIBRARIES-dependency.patch -> this pull request adds Flann as an optional dependency for tests.
0003-Fix-script-extension.patch -> pull request
0003-Fix-shebang-in-subfolders-of-demos.patch -> main handles the patch
0004-Fix-FindPython-module-check.patch -> pull request
> Debian patches fix

- .github/workflows/wheels.yaml
- CMakeModules/FindPython.cmake
- CMakeModules/OMPLUtils.cmake
- README.md
- demos/BouncingBallPlanning.cpp
- demos/CMakeLists.txt
- demos/PinballPlanning.cpp
- demos/SSTPinballPlanning.cpp
- demos/multicopter/CommonMath/ConvexObj.h
- demos/multicopter/CommonMath/RectPrism.h
- demos/multicopter/CommonMath/Rotation.h
- demos/multicopter/CommonMath/Trajectory.h
- demos/multicopter/CommonMath/Vec3.h
- demos/multicopter/MulticopterPlanning.cpp
- demos/multicopter/Polyfit.h
- demos/multicopter/Quartic.cpp
- demos/multicopter/Quartic.h
- doc/markdown/download.md.in
- doc/markdown/installation.md
- py-bindings/pyproject.toml
- py-bindings/setup.py
- scripts/CMakeLists.txt
- src/ompl/base/spaces/HybridStateSpace.h
- src/ompl/base/spaces/HybridTimeStateSpace.h
- src/ompl/base/spaces/src/HybridStateSpace.cpp
- src/ompl/base/spaces/src/HybridTimeStateSpace.cpp
- src/ompl/control/planners/rrt/HyRRT.h
- src/ompl/control/planners/rrt/src/HyRRT.cpp
- src/ompl/control/planners/sst/HySST.h
- src/ompl/control/planners/sst/src/HySST.cpp
Implementation of two new planners (HyRRT and HySST) for planning for hybrid systems. 
**Relevant Publications**
[1] N. Wang and R. G. Sanfelice, "A Rapidly-Exploring Random Trees Motion Planning Algorithm for Hybrid Dynamical Systems," 2022 IEEE 61st Conference on Decision and Control (CDC), Cancun, Mexico, 2022, pp. 2626-2631, doi: 10.1109/CDC51059.2022.9992444. (https://ieeexplore.ieee.org/document/9992444)
[2] N. Wang and R. G. Sanfelice, "HySST: An Asymptotically Near-Optimal Motion Planning Algorithm for Hybrid Systems," 2023 62nd IEEE Conference on Decision and Control (CDC), Singapore, Singapore, 2023, pp. 2865-2870, doi: 10.1109/CDC49753.2023.10383466. (https://ieeexplore.ieee.org/document/10383466)
[3] B. Xu, N. Wang and R. G. Sanfelice, "cHyRRT and cHySST: Two motion planning …
> Added HyRRT and HySST
