- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
With the current BITstar code, the following error appears when trying to run omplapp gui:
Traceback (most recent call last):
File "../../gui/ompl_app.py", line 53, in <module>
ompl.initializePlannerLists()
File "/home/jvgomez/Desktop/omplapp/ompl/py-bindings/ompl/__init__.py", line 107, in     initializePlannerLists
ompl.geometric.planners = ompl.PlanningAlgorithms(ompl.geometric)
File "/home/jvgomez/Desktop/omplapp/ompl/py-bindings/ompl/__init__.py", line 30, in __init__
self.addPlanner(obj2)
File "/home/jvgomez/Desktop/omplapp/ompl/py-bindings/ompl/__init__.py", line 89, in addPlanner
print r, int(r)
ValueError: invalid literal for int() with base 10: '1u'
This PR solves this issue. Furthermore, it is now consistent with other planners.
> Fixed omplapp issue with BITstar

- src/ompl/base/OptimizationObjective.h
- src/ompl/base/objectives/src/MaximizeMinClearanceObjective.cpp
- src/ompl/base/src/OptimizationObjective.cpp
- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/datastructures/IntegratedQueue.h
- src/ompl/geometric/planners/bitstar/datastructures/src/IntegratedQueue.cpp
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
- src/ompl/tools/config/MagicConstants.h
These are the changes for option (1) as in Issue [#156](https://bitbucket.org/ompl/ompl/issues/156), moving the margin into only `isSatisfied`. I made the change faithful to the previous behaviour, though I am somewhat surprised to notice that the margin actually makes it harder to satisfy the specified threshold.
> Margin free cost comparisons

- src/ompl/base/OptimizationObjective.h
- src/ompl/geometric/planners/rrt/src/RRTstar.cpp
- tests/geometric/2d/2dcircles_optimize.cpp
I was able to replicate the errors in 2dcircles_optimize **with** the old margin in the comparison. They appear to occur because, sometimes, the planner simply doesn't find a better solution than the initial one.
This code relaxes tests enough that it will pass in the situations. Whether that is too much of a relaxation is an open question.
Will rebase once it's ready to go.
> Fix for 2dcircles_optimize

- src/ompl/base/goals/src/GoalStates.cpp
- src/ompl/base/samplers/InformedStateSampler.h
- src/ompl/base/samplers/informed/PathLengthDirectInfSampler.h
- src/ompl/base/samplers/informed/RejectionInfSampler.h
- src/ompl/base/samplers/informed/src/PathLengthDirectInfSampler.cpp
- src/ompl/base/samplers/informed/src/RejectionInfSampler.cpp
- src/ompl/base/samplers/src/InformedStateSampler.cpp
- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/datastructures/IntegratedQueue.h
- src/ompl/geometric/planners/bitstar/datastructures/Vertex.h
- src/ompl/geometric/planners/bitstar/datastructures/src/IntegratedQueue.cpp
- src/ompl/geometric/planners/bitstar/datastructures/src/Vertex.cpp
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
- src/ompl/geometric/planners/rrt/InformedRRTstar.h
- src/ompl/util/ProlateHyperspheroid.h
- src/ompl/util/RandomNumbers.h
- src/ompl/util/src/ProlateHyperspheroid.cpp
- src/ompl/util/src/RandomNumbers.cpp
This is the last PR I had in my queue. It's a couple things.
1. Support for multiple starts/goals in `PathLengthDirectInfSampler`,
2. Support for the MoveIt! workflow in `BIT*`,
3. Support for planning problems with infinite bounds in `BIT*`,
4. A couple other new ideas for `BIT*`, and
5. Documentation updates for `PathLengthDirectInfSampler,` `InformedRRT*` and `BIT*` to support the upcoming release.
Will rebase when it's ready to go.
> Informed sampling multistart/goal support, BIT* MoveIt! and infinite problem support

- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
A much better default-way for `BIT*` to handle the "size" of the first batch of an infinite planning problem. Instead of assuming unit measure, estimates it as that of a (hyper)cube proportional to the distance between start and goal. Provides some relation to the order-of-magnitude of the problem, and moves the `std::isfinite` check on the measure to just `setup`.
> BIT*: Infinite problem domain fix

- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/datastructures/IntegratedQueue.h
- src/ompl/geometric/planners/bitstar/datastructures/Vertex.h
- src/ompl/geometric/planners/bitstar/datastructures/src/IntegratedQueue.cpp
- src/ompl/geometric/planners/bitstar/datastructures/src/Vertex.cpp
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
- src/ompl/geometric/planners/rrt/src/InformedRRTstar.cpp
It turns out that the regression bug was a weird and subtle timing-related thing in my private experimental code. I rebased a commit to update a description in the header file though, and it won't let me reopen the previous commit.
The description was:
> The existing k-nearest version of BIT* is only an approximation. This is a version that is correct. Also cleaned up some other things while I was in there.
This is only changes to BIT* and a cosmetic change to Informed RRT*, so hopefully it'll be easy to merge?
> BIT*: Correct k-nearest version

- src/ompl/geometric/planners/fmt/FMT.h
- src/ompl/geometric/planners/fmt/src/FMT.cpp
Resampling strategy for FMT.  Work included in the paper of the [Bidirectional FMT paper](http://arxiv.org/pdf/1507.07602.pdf(http://arxiv.org/pdf/1507.07602.pdf) (that planner will be included in another PR). This enormously increases the success rate of the planner with very little impact in the computation time.
Other minor modifications (simplifications) have been included.
> Extended FMT: add resampling strategy if FMT is not able to find a solution.

- src/ompl/geometric/planners/prm/SPARS.h
- src/ompl/geometric/planners/prm/SPARStwo.h
- src/ompl/geometric/planners/prm/src/SPARS.cpp
- src/ompl/geometric/planners/prm/src/SPARStwo.cpp
Since the minimum required boost is now greater than 1.48, we can remove this hack:
> The InterfaceHash structure is wrapped inside of this struct due to a compilation error on
> GCC 4.6 with Boost 1.48.  An implicit assignment operator overload does not compile with these
> components, so an explicit overload is given here.
> Remove this struct when the minimum Boost requirement is > v1.48.
I've been running this fix on my fork of SPARS for some time now with no problems
> Remove compatibility wrapper struct for incompatibility with prev Boost and GCC

- src/ompl/tools/thunder/Thunder.h
- src/ompl/tools/thunder/src/SPARSdb.cpp
- src/ompl/tools/thunder/src/Thunder.cpp
Ig Manu reported:
> I'm trying to implement a path planning
> algorithm, but with the Thunder framework I keep getting an error, when
> doPostProcessing() is called (everything before works fine)
> 
> Vector Subscript is out of Range. In Sparsedb.cpp line 815:
> i == addedStateIDs[usedIDTracker]
> 
> Do you have an idea, what could cause this? I'm building on Visual Studio 2015.
This PR changes one line to have an extra check for this error.
Also small variable name formatting fix included.
> Fix vector subscript out of range

- src/ompl/base/samplers/MinimumClearanceValidStateSampler.h
- src/ompl/base/samplers/src/MinimumClearanceValidStateSampler.cpp
Implements a sampler as described in [Sparse roadmap spanners for asymptotically near-optimal motion planning](http://ijr.sagepub.com/content/33/1/18.full.pdf) by Andrew Dobson and Kostas E. Bekris. This sampler only accepts states "for some clearance cl > 0". This is a missing component in the current SPARS and SPARS2 implementation in OMPL, but I am using it in my current work.
This PR also includes an optional settings for state validity checkers that would allow iterative or APPROXIMATE checkers that do an iterative search in increasing distances from the sampled state to have get/set that search distance. This search distance could/should correspond to the above sampler's minimum clearance threshold. The sampler I'm using this setting for is a 2D grid based on PPM image files, but I …
> New valid state sampler w/min obstacle clearance threshold

- src/ompl/base/PlannerDataStorage.h
Original implementation takes n^2 - was very slow for my Sparse graph research
New version is n
> Speedup storing edges in PlannerData

- src/ompl/geometric/PathGeometric.h
- src/ompl/geometric/src/PathGeometric.cpp
I want to re-use the same SharedPtr of PathGeometric being passed into a function and feel like this is cleaner than creating a new one.
> Allow a PathGeometric class to be cleared

- src/ompl/geometric/planners/rrt/RRTXstatic.h
- src/ompl/geometric/planners/rrt/src/RRTXstatic.cpp
Similarly to the recent update on RRTstar, the constants for the radius of the ball and the number of nearest neighbors has been updated in RRTXstatic to guarantee optimality.
> Changed RRTXstatic to use r_rrt and k_rrt instead of r_rrg and k_rrg

- CMakeLists.txt
- CMakeModules/CompilerSettings.cmake
These two commits make OMPL buildable with the latest Yocto. Particularly it fixes a compatibility issue with gcc6 and makes setting RPATH optional to conform with Opembedded-Core's QA checks.
> Fix Yocto builds

- src/ompl/base/samplers/informed/src/PathLengthDirectInfSampler.cpp
- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/bitstar/datastructures/src/ImplicitGraph.cpp
- src/ompl/geometric/planners/bitstar/src/BITstar.cpp
1. Allow `BITstar::setup()` to run without a problem definition and delay the necessary work until `BITstar::solve()` calls `Planner::checkValidity()` (which will then recall `BITstar::setup()`)
2. Allow `PathLengthDirectInfSampler` to support `STATE_SPACE_UNKNOWN` with a warning.
3. Initialize `BITstar` member variables in the header instead of constructor as per style.
4. Revert `BITstar::ImplicitGraph::removeSample()` and `BITstar::ImplicitGraph::removeVertex()` to taking a local copy of the removed data to avoid a low-frequency segfault. [See issue here](https://bitbucket.org/ompl/ompl/issues/364/code-cleanup-breaking-bit).
5. Fix segfault in `BITstar::ImplicitGraph::clear()` caused by an already cleared pointer.
> BIT* and PathLengthDirectInfSampler fixes

- src/ompl/datastructures/NearestNeighborsFLANN.h
I encountered the following two errors when including `NearestNeighborsFLANN.h` in two different cpp files within the same library:
Missing `Exception.h` include:
```cpp
/home/marius/exploration_ws/devel/include/ompl/datastructures/NearestNeighborsFLANN.h:187:19: error: use of undeclared identifier 'Exception'
throw Exception("No elements found in nearest neighbors data structure");
^
1 error generated.
```
Missing `inline`:
```cpp
CMakeFiles/bla_lib.dir/src/bla.cpp.o: In function `ompl::NearestNeighborsFLANN<double, flann::L2<double> >::createIndex(flann::Matrix<double> const&)':
/home/marius/exploration_ws/src/bla/bla/src/bla.cpp:(.text+0x0): multiple definition of `ompl::NearestNeighborsFLANN<double, flann::L2<double> >::createIndex(flann::Matrix<double> const&)'
```
This happened …
> Fix redefinition and missing include errors

- src/ompl/base/samplers/BridgeTestValidStateSampler.h
- src/ompl/base/samplers/src/BridgeTestValidStateSampler.cpp
Implements the bridge-test sampler, described in "The bridge test for sampling narrow passages with probabilistic roadmap planners" by Hsu, et al.
Has been tested for a spherical robot on the plane:
Left: Obstacle-Based Sampler (ObstacleBasedValidStateSampler.h), Right: Bridge-Test Sampler (BridgeTestValidStateSampler.h)
> Bridge Test Implementation

- src/ompl/geometric/planners/bitstar/datastructures/src/ImplicitGraph.cpp
Correct the radius used by BIT* to be the same as described in the associated papers (e.g., RRT* radius).
> BIT* radius as published.

- src/ompl/base/TypedSpaceInformation.h
The missing parameter is caught by newer GCC versions doing stricter template checks.
> Add missing parameter in TypedSpaceInformation::cloneTypedState()

- src/ompl/base/src/StateSpace.cpp
Hi,
It seems to me that this check is wrong. It ensures that d(s1,s2) = d(s1,s3)+d(s3,s2), while it is expected to ensure that (triangle inequality) d(s1,s2) <= d(s1,s3)+d(s3,s2). Otherwise it may be the exception message that should be corrected.
Here is how I would have done it.
Hope I'm not misunderstanding something here :)
Cheers,
JW
> fix triangle inequality check in StateSpace::sanityChecks

- CMakeLists.txt
- Avoids overflow error when running under Valgrind
- Resolves issue described in https://bitbucket.org/ompl/ompl/issues/543
> Set BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS definition

- src/ompl/geometric/planners/est/EST.h
- src/ompl/geometric/planners/est/src/BiEST.cpp
- src/ompl/geometric/planners/rrt/TRRT.h
- src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
Some planners have dependent parameters  on other primary parameters which can be set externally using the setParam().  However, if the primary  parameters  change and setup is not called afterwards, in the case of EST planner and the TRRT planner  the dependent parameters are not updated . This PR fixes this by updating the dependent  parameters when the setters of the original parameters are called.
> Bug/dependent parameters not updated for EST and TRRT

- src/ompl/geometric/SimpleSetup.h
- src/ompl/geometric/src/SimpleSetup.cpp
This fixes an inconsistency between what `SimpleSetup` and `ProblemDefinition` considers an exact solution by passing through `SimpleSetup`'s calls.
This specifically removes the
```
pdef_->getSolutionDifference() < std::numeric_limits<double>::epsilon()
```
check that `SimpleSetup` was doing to decide if a solution was exact and instead reports what the planner actually returned in its `PlannerStatus` flag.
The existing behaviour caused a bug with RRTConnect when searching from a goal area (https://github.com/ompl/ompl/pull/683).
> SimpleSetup cleanup

- src/ompl/geometric/planners/fmt/src/FMT.cpp
Using `std::numeric_limits<double>::infinity()` assumes that we are minimizing the objective. The fix allows to use maximization objectives (e.g., max min clearance http://ompl.kavrakilab.org/optimizationObjectivesTutorial.html).
> Use optimization objective to initialize cost in FMT*

- src/ompl/datastructures/BinaryHeap.h
I think this should be a const reference for two reasons. 1) A const reference communicates that the method does not modify the input, and 2) right now `void BinaryHeap::insert(const std::vector<_T> &list)` is broken, because non-const references can not be bound to const references. On line 161 in `ompl/source/ompl/datastructures/BinaryHeap.h` we have:
```c++
Element *element = newElement(list[i], pos);
```
but this fails to compile because `list[i]` effectively returns a `const _T&`, which pre-fix `newElement` tries to bind to a `_T&`. (Sorry, I can't seem to figure out how to comment code directly in the file anymore...).
Since this PR is in quick succession to the last: If I were to find more small fixes, would you prefer it if I held them back until I have found a bunch of them and …
> Make data reference const in newElement method of BinaryHeap

- src/ompl/base/spaces/constraint/src/ConstrainedStateSpace.cpp
I ran into an issue when trying to used constrained planning functionality in OMPL, where if you made the range value for a planner  small (0.01) it would try to index outside the `geodesic`. These changes fix the issue but not being familiar with the code I am not certain this is the correct fix and there may be some other issue elsewhere in the code.
> Fix issue in ConstrainedStateSpace geodesicInterpolate when planner range value is small

- src/ompl/base/src/PlannerTerminationCondition.cpp
It seems that interval is ignored.
I only confirmed that the build passed after this change, and have not confirmed that it actually works
> pass interval in timedPlannerTerminationCondition constructor

- src/ompl/base/src/ProjectionEvaluator.cpp
compilation with current Eigen master branch failed with c++17 enabled, see the error message below:
```
In file included from /usr/local/include/eigen3/Eigen/Core:261:0,
from /opt/ros/melodic/src/ompl/src/ompl/base/ProjectionEvaluator.h:49,
from /opt/ros/melodic/src/ompl/src/ompl/base/StateSpace.h:43,
from /opt/ros/melodic/src/ompl/src/ompl/base/src/ProjectionEvaluator.cpp:37:
/usr/local/include/eigen3/Eigen/src/Core/CoreEvaluators.h: In instantiation of ‘class Eigen::internal::unary_evaluator<Eigen::CwiseUnaryOp<double (*)(double) throw (), const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<double, double>, const Eigen::Ref<Eigen::Matrix<double, -1, 1> >, const Eigen::Map<const Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> > > >, Eigen::internal::IndexBased, …
```
> Fix compilation with Eigen master branch

- doc/markdown/developers.md
- src/ompl/base/samplers/informed/PathLengthDirectInfSampler.h
- src/ompl/geometric/planners/bitstar/BITstar.h
- src/ompl/geometric/planners/rrt/InformedRRTstar.h
- src/ompl/geometric/planners/rrt/SORRTstar.h
- src/ompl/util/ProlateHyperspheroid.h
- src/ompl/util/RandomNumbers.h
Hi @mamoll ,
I was waiting to update the paper references once I had the full publication info for the BIT* IJRR paper. I have that now, so this is just a switch from conference refs to journal refs for Informed RRT*, SORRT*, and BIT*.
(And a link to me that I found when searching for paper refs to update).
Hoping it's no work for you to merge.
Thanks,
Jon
> Update paper references for Informed RRT*, SORRT*, and BIT*.

- py-bindings/headers_base.txt
- src/ompl/base/goals/GoalSpace.h
- src/ompl/base/goals/src/GoalSpace.cpp
Hi Mark,
This is a simple version of a goal area defined by the user via a `StateSpace`. I thought it may be useful to the main branch as, while it's limited, there's currently no nonabstract area goals in OMPL.
Jon
> Nonabstract goal area defined by the limits of a second StateSpace.

- src/ompl/geometric/planners/informedtrees/AITstar.h
- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
Summary:
1. Add `nullptr` check when calling `AITstar::trackApproximateSolutions`
2. Enable tracking approximate solutions by default
3. Continuously track approximate solutions (previously got best approximate solution only before `solve` returns)
Reasoning:
1. AIT* tries to initialize its approximate solution cost with `OptimizationObjective::infiniteCost`, which needs access to an optimization objective. Calling `AITstar::trackApproximateSolutions` when the planner hasn't been `setup` yet resulted in a segfault because AIT* didn't know of the optimization objective yet. This PR adds the necessary check. (Without an optimization objective, AIT* can't know how to initialize the approximate solution cost and  therefore simply refrains from doing so.)
2. This seems to be the default for …
> Add nullptr check when setting AIT* to track approximate solutions

- src/ompl/geometric/planners/informedtrees/AITstar.h
- src/ompl/geometric/planners/informedtrees/aitstar/ImplicitGraph.h
- src/ompl/geometric/planners/informedtrees/aitstar/src/ImplicitGraph.cpp
- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
Hi Mark,
The problem was that the connection radius of the edge-implicit RGG that AIT* searches was not appropriate for problems in which some dimensions are (much) larger than others (the theory holds for the unit cube). This PR implements an option that turns AIT*'s r-disc RGG into a k-nearest RGG, which seems to be more robust to dimensions of unequal extent. I've set the k-nearest model as the default option.
With this, AIT* to solved the problem referenced in #721 in less than 10 seconds 10/10 times on my machine.
> Implement k-nearest connection model in AIT*'s RGG

- src/ompl/geometric/planners/informedtrees/AITstar.h
- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
- tests/geometric/2d/2dcircles_optimize.cpp
Hi Mark,
As far as I understand, `test_2d_circles_opt_geometric` makes the implicit assumption that the planners find an exact solution to the problem. Otherwise the checks on lines 152, 156, 160, and 173 don't make sense:
- Line 152: `BOOST_CHECK(!opt->isCostBetterThan(prev_cost, new_cost));` If the solution is approximate, this should be allowed happen.
- Line 156: `BOOST_CHECK(!pdef->hasApproximateSolution());` Checks for exact solutions, but the condition of the enclosing `while` prevents this check from being reached when the planner doesn't find an exact solution and uses all the solution time.
- Line 160: `BOOST_CHECK(!opt->isCostBetterThan(ini_cost, prev_cost));` This can happen if the initial solution is approximate.
- Line 173: `BOOST_CHECK(!opt->isCostBetterThan(prev_cost, …
> Make unit test assumption explicit

- src/ompl/geometric/planners/prm/src/LazyPRM.cpp
This fixes a bug in 1.5.0 in LazyPRM.  When the first constructor (that uses base::SpaceInformationPtr) is called, and then setRange() is called before setMaxNearestNeighbors() or setup() [this is EXACTLY how the default moveit setup is calling this], then setDefaultConnectionStrategy() is called before a NearestNeighbor pointer (nn_) is set up which then crashes OMPL in the LazyPRM constructor.
> Fix for crash in LazyPRM constructor (noticed in default MoveIt setup)

- CMakeLists.txt
Reference:
* https://github.com/ros-industrial/noether/blob/80d95795af4c8bfec4ac508ef602cbeb7c157528/noether_filtering/CMakeLists.txt#L185-L187
* https://github.com/ros-industrial/noether/pull/91
Fixes: https://github.com/ompl/ompl/issues/753
cc @SteveMacenski @mikaelarguedas
> Register package with the ament index for ROS2 installation

- demos/quotientspace/QuotientSpacePlanningKinematicChain.cpp
This is a tiny change that fixes a sign-compare warning that I got curious about when building in debug mode.
To me it looks like the links could be `unsigned int`s, but can you please verify this, @aorthey ? Thanks!
> Sign compare warning in assert statement of quotient space demo

- src/ompl/geometric/planners/informedtrees/BITstar.h
- src/ompl/geometric/planners/informedtrees/bitstar/src/ImplicitGraph.cpp
- src/ompl/geometric/planners/informedtrees/src/BITstar.cpp
The main purpose of this PR is to remove the planner progress properties in BIT* that are not thread-safe (namely getting number of current vertices in graph and getting number of total samples). This should fix #779, @jediofgever can you please confirm?
I also changed the default name of BIT* from `"BITstar"` to `"kBITstar"` since by default BIT* is instantiated with a k-nearest connection model (since c08da89), which silences a warning. I also took the chance to clean up some code as it came up.
> Clean up BIT* planner progress properties

- src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
I had come across RRTConnect returning approximate solutions that start at goal state.
As I believe this is not the expected behaviour, this PR prevents this from happening.
> Prevent RRTConnect returning approximate solutions from goal

- src/ompl/geometric/src/SimpleSetup.cpp
The `SimpleSetup` class is absolutely awesome but it currently has a limitation where even if you set a custom objective via
```cpp
simple_setup.setOptimizationObjective(my_objective);
```
it doesn't make the `PathSimplifier` aware of that objective and it simply defaults to optimizing for the shortest path length. This can be seen in the plot below
In it, I have set a custom objective which includes optimizing for the shortest path and a potential field that should force the path to the wall on the right side. The solution states in purple are correctly optimized and sit on the right but after I run path simplification I get the path in blue which disregards my custom objective.
With the changes in this MR, running the same experiment results in 
(the transparent line is the reference …
> make PathSimplifier aware of the objective in SimpleSetup

- src/ompl/geometric/planners/informedtrees/bitstar/src/ImplicitGraph.cpp
This PR fixes a small issue that @gammell and I noticed when BIT* plans in compound spaces where the informed set of some subspaces can be sampled directly.
Here's how I understand what the problem was: If sampling from a compound state space with `RealVectorStateSpace`s as components, then direct informed sampling is used for these components. To support just-in-time sampling, BIT* samples "shells" of the informed set in these components. These shells are defined by a minimum and maximum cost. The issue with initializing `sampledCost_` as the minimum possible cost to solve the problem is that some of that cost might come from non-`RealVectorStateSpace` components of the compound state space, e.g., the angular component in SE(2). If this is the case, then the center of the informed set in …
> Set the sampled cost to identity when adding a new batch in BIT*

- src/ompl/base/samplers/informed/src/PathLengthDirectInfSampler.cpp
@gammell I've separated the actual changes from the clang-format changes to make it easier for you to see what actually changed (ed64860).
> Support Dubin and Reeds Shepp spaces with the direct inf sampler

- src/ompl/geometric/planners/rrt/RRTConnect.h
- src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
Hi Mark
A small change for RRT-Connect:
I think it's important that planners can be visualized iteration by iteration. One way to achieve this is to repeatedly call solve with an always-terminating ptc and get the planner data after each call. This small change ensures that RRT-Connect alternates between expanding the start and goal trees in this scenario.
cc: @gammell
> Ensure RRT-Connect alternates expansion of trees

- src/ompl/base/samplers/informed/src/PathLengthDirectInfSampler.cpp
- src/ompl/geometric/PathSimplifier.h
This PR adds more detail to exceptions for compound state-spaces which help in diagnosing setup errors. 
It also enables compound state-spaces which have one RealVectorStatespace to work as if they were non-compound-state spaces.
> PathLengthDirectInfSampler: Add support for nested RealVectorStatespace

- src/ompl/base/OptimizationObjective.h
- src/ompl/base/objectives/ControlDurationObjective.h
- src/ompl/base/objectives/src/ControlDurationObjective.cpp
- src/ompl/base/src/OptimizationObjective.cpp
- src/ompl/control/planners/sst/src/SST.cpp
OptimizationObjective was designed for geometric planning and cannot
associate costs with ompl::control::Control. This addresses this short-
coming in the following way:
* New controlCost(control, steps) function (defaults to identityCost)
* New ControlDurationObjective, which minimizes the total time needed
* Support for controlCost() in the control-space version of SST
Other typical control-space costs include control-integral costs, but
are application-specific and can be now defined by the user by creating
a derived class inheriting from OptimizationObjective().
> Optimization Objectives: Add support for control-space planners

- src/ompl/control/planners/sst/src/SST.cpp
- src/ompl/geometric/planners/sst/src/SST.cpp
SST currently just prints an information when a new solution is found.
This change calls the (optional) callback that a user can set to get
informed about new solutions, similar to BIT*, RRT* etc.
> SST: Add support for IntermediateSolutionCallback of problem definition

- src/ompl/base/spaces/ReedsSheppStateSpace.h
the inherited validSegmentCount is calculated by 2D distances between states, which causes the undersampling issue to the ReedsShepp curves connecting two states near in 2D positions.
> override the validSegmentCount function of the ReedsSheppState Space

- tests/CMakeLists.txt
The rest of the code compiles fine when switching the OMPL C++ standard to C++17 with this one-line change:
```diff
--- a/CMakeModules/CompilerSettings.cmake
+++ b/CMakeModules/CompilerSettings.cmake
@@ -1,4 +1,4 @@
-set(CMAKE_CXX_STANDARD 14)
+set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```
> preemptive c++17 compiler fix for FLANN

- src/ompl/geometric/planners/informedtrees/bitstar/src/Vertex.cpp
This is a bug fix concerning issue #902.
The iterator can become null and so even if the found flag is set to true, it crashes in the next pass before exiting the loop...
> fix encounter of possibly null iterator in for loops

- src/ompl/geometric/planners/cforest/src/CForest.cpp
Exceptions in worker threads cannot be caught by user code and should therefore be handled within the worker thread
> Catch (and print) exceptions in CForest::solve

- src/ompl/base/terminationconditions/CostConvergenceTerminationCondition.h
- src/ompl/base/terminationconditions/IterationTerminationCondition.h
Added missing header guards to CostConvergenceTerminationCondition.h and IterationTerminationCondition.h
> Added missing header guards to header of derived classes of ompl::base::PlannerTerminationCondition 

- src/ompl/base/Planner.h
- src/ompl/base/src/Planner.cpp
Signed-off-by: Tyler Weaver <tyler@picknik.ai>
This fixes a bug that occurs with this call stack:
```
#3 0x7f9ad6386df1 in ompl::base::SpaceInformation::freeState(ompl::base::State*) const /home/tyler/code/ws_miso_asan/src/ompl/src/ompl/base/SpaceInformation.h:240
#4 0x7f9ad6607711 in ompl::base::PlannerInputStates::clear() /home/tyler/code/ws_miso_asan/src/ompl/src/ompl/base/src/Planner.cpp:171
#5 0x7f9ad6607fae in ompl::base::PlannerInputStates::use(ompl::base::ProblemDefinition const*) /home/tyler/code/ws_miso_asan/src/ompl/src/ompl/base/src/Planner.cpp:229
#6 0x7f9ad6607f41 in ompl::base::PlannerInputStates::use(std::shared_ptr<ompl::base::ProblemDefinition> const&) /home/tyler/code/ws_miso_asan/src/ompl/src/ompl/base/src/Planner.cpp:219
#7 0x7f9ad6607a90 in …
```
> Fix use-after-free in PlannerInputStates::clear()

- src/ompl/base/src/PlannerTerminationCondition.cpp
Running with thread sanitizer, `-fsanitize=thread`, exposed possible race conditions in PlannerTerminationCondition. I'm not too familiar with OMPL's threading model, but changing the offending bools to `std::atomic<bool>` seems to have resolved the issue.
``` Write of size 1 at 0x7b1400001949 by main thread:
#0 ompl::base::PlannerTerminationCondition::PlannerTerminationConditionImpl::stopEvalThread() <null> (navigator_test+0xe89820)
#1 ompl::base::PlannerTerminationCondition::PlannerTerminationConditionImpl::~PlannerTerminationConditionImpl() <null> (navigator_test+0xe895cb)
#2 void __gnu_cxx::new_allocator<ompl::base::PlannerTerminationCondition::PlannerTerminationConditionImpl>::destroy<ompl::base::PlannerTerminationCondition::PlannerTerminationConditionImpl>(ompl::base::PlannerTerminat …
```
> made PlannerTerminationCondition bools atomic

- src/ompl/geometric/planners/prm/src/LazyPRM.cpp
While using LazyPRM I encountered the issue that the planner sometimes ignored max planning time. As pointed out by #852 this is caused by a while loop that tries to construct a solution and this might exceed a specified max. planning time and thus violate a termination criteria. This PR fixes the issue by additionally checking the criteria as part of the while loop. It partially fixes #943 although I have not figured out why so many new states get created.
> LazyPRM: Check termination criteria while trying to construct a solution

- CMakeModules/FindPython.cmake
`inspect.getfile` doesn't seem to work with python3.10 and higher for modules like `PyQt5`:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 778, in getfile
raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'PyQt5' (<_frozen_importlib_external._NamespaceLoader object at 0x1100dd660>)> is a built-in module
```
> fix detection of python module path and version

- src/ompl/base/terminationconditions/src/CostConvergenceTerminationCondition.cpp
Currently the captured `this` pointer becomes a dangling reference as soon the original `CostConvergenceTerminationCondition` goes out of scope. This lead to a `solutionsWindow` of 0 which made this quite useless, current average being always `inf`.
Relates to #907 
@rhaschke tagging you due to initiating #906
> avoid dangling reference to CostConvergence parameters

- tests/CMakeLists.txt
- tests/tools/test_experience_planning.cpp
This PR add test for experience base planner.
I think this test is useful for ensuring the core behavior of newly added algorithm is same as the other experience-based planner. 
For example, in my opinion, for https://github.com/ompl/ompl/pull/783 to be merged, adding the test using the same interface with lightning and thunder, though some of the common test could be changed, is expected. 
1. The test tests both case where algorithm is specified and not. This is because, algorithm's initialization/seutp timing is different for both case.
Actually by writing this test, I found behavior mismatches between lightning and thunder, and, the same tests for Thunder will not pass.  I will fix these issues/difference after this PR is merged and this PR is the first step for that.
lightning store …
> test: add test for experience based planner

- CMakeModules/FindPython.cmake
This PR enables OMPL Python bindings to be compiled on Ubuntu for ARM. To be able to build ompl.Dockerfile, you would additionally need to remove libspot, as the PPA doesn't have an `arm64` package.
- Further discussion can be found in #958
> Add ARM Ubuntu triplet

- src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
Fixes #712 - adding states should be reversed when extending goal tree.
> Fix for RRTConnect with intermediate states

- src/ompl/control/src/SpaceInformation.cpp
> Existence check to prevent segfault on uninitialized print in control::SpaceInformation

- py-bindings/generate_bindings.py
For some reason, `SpecificParam<std::string>` appears as either `SpecificParam<std::string>` or `SpecificParam<std::basic_string<char>>` - there is some code to try and figure out what strings are in castxml, but for some reason it is inconsistent for `SpecificParam`, particularly on Ubuntu 20.04.
> Added try/except for string SpecificParam

- src/ompl/geometric/planners/informedtrees/aitstar/src/ImplicitGraph.cpp
Executing AIT* with my environment is in an infinite loop.
In a simple environment, it doesn't have any problems, but in a high-complexity environment planner is stuck.
A similar issue was reported in the moveit repo [[moveit#3329](https://github.com/ros-planning/moveit/issues/3329)](https://github.com/ros-planning/moveit/issues/3329).
I added a termination condition to prevent this situation.
> fix: AIT* infinite loop

- src/ompl/util/src/RandomNumbers.cpp
Removes a potential overflow in time computation - not terribly important as the bits were just used to seed the generator. Fixes #887
> Use time_since_epoch() to get seed

- py-bindings/generate_bindings.py
Removed two more functions from EIT*'s Python bindings that threw symbol not found errors when trying to load the library.
> Additional exclusions for EIT* Python bindings

- src/ompl/geometric/planners/informedtrees/eitstar/RandomGeometricGraph.h
- src/ompl/geometric/planners/informedtrees/eitstar/src/RandomGeometricGraph.cpp
I am currently trying to use the informed tree planners in MoveIt, however, when testing EIT*/EIRM* the planner is failing to sample the goal region. I get the following error:
```shell
[ERROR] [1676514489.653650246]: arm/arm[EITstar]: No solution can be found as no goal states are available
[ERROR] [1676514489.653739781]: arm/arm[EITstar]: No solution can be found as no goal states are available
[ERROR] [1676514489.653818728]: arm/arm[EITstar]: No solution can be found as no goal states are available
[ERROR] [1676514489.653867118]: arm/arm[EITstar]: No solution can be found as no goal states are available
[ WARN] [1676514489.653914669]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000329 seconds
[ WARN] [1676514489.653941393]: Timed out
[ WARN] …
```
> Fix EIT* failing to sample the goal region

- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
Currently, the `objective_` pointer is only set when calling the `setup()` method. However, this pointer is referenced in the `clear()` method, which means that if the user calls `AITstar::clear()` before calling `AITstar::setup()` there will be a segmentation fault.
As the costs will be set to the `infinity cost` when the `setup()` method is called, I changed the `clear` method to set the costs as NaN.
> Fix AIT* segfault when calling clear before setup

- src/ompl/base/spaces/DubinsStateSpace.h
- src/ompl/base/spaces/src/DubinsStateSpace.cpp
`validSegmentCount` is used to determine the number of interpolation points to use for collision checking a segment.
`DubinsStateSpace` incorrectly delegated to the default `CompoundStateSpace::validSegmentCount` implementation, which evaluates each subspace independently and returns the highest value.
This patch returns to the basic `StateSpace` behavior, computing a count based on edge length -- in this case, the length of the Dubins path.
Fixes #811.
> Fix incorrect validSegmentCount in DubinsStateSpace

- demos/constraint/ConstrainedPlanningCommon.py
- demos/constraint/ConstrainedPlanningTorus.py
- py-bindings/generate_bindings.py
- Update to the signature needed to find & replace in Python binding generation needed for constrained planning.
- Optional tool import
Fixes #1007
> Fix for constrained planning python bindings

- src/ompl/base/spaces/constraint/src/AtlasStateSpace.cpp
- src/ompl/base/src/PlannerData.cpp
In PLY files it is more common and well supported to use a `uchar` for the number of face vertices and an `int` for the vertex indices. These are also the types used in the PLY format description. Certain software (e.g. [Meshlab](https://www.meshlab.net/)) doesn't support using a `uint` for either type.
Although this is arguably a bug in Meshlab, it doesn't hurt if OMPL outputs PLY files in a more widely supported format, especially considering there are no drawbacks for doing so.
http://paulbourke.net/dataformats/ply/
> Use more conservative types in PLY files

- src/ompl/geometric/planners/informedtrees/src/AITstar.cpp
- src/ompl/geometric/planners/informedtrees/src/EITstar.cpp
Related to #874 
This PR adds a call to `getIntermediateSoluitionCallback` to AIT* and EIT* planners, so the `CostConvergenceTermination`  (and `CForest`) can be used with them.
On a side note, the planner specs were already setting `canReportIntermediateSolutions` as true.
> AIT*/EIT*: Add support for IntermediateSolutionCallback

- py-bindings/headers_base.txt
The [deterministic samplers](https://ompl.kavrakilab.org/classompl_1_1base_1_1DeterministicStateSampler.html) were missing from the Python binding generation. This adds the header to generate them in the `base` module.
> Added deterministic samplers to Python binding generation

- py-bindings/generate_bindings.py
> Add back in alternative signature for Python bindings for constrained planning

- demos/SpaceTimePlanning.py
- py-bindings/generate_bindings.py
- py-bindings/headers_base.txt
- py-bindings/headers_geometric.txt
- py-bindings/ompl_py_base.h
- src/ompl/base/samplers/ConditionalStateSampler.h
- src/ompl/base/samplers/src/ConditionalStateSampler.cpp
- src/ompl/geometric/planners/rrt/STRRTstar.h
- src/ompl/geometric/planners/rrt/src/STRRTstar.cpp
This MR creates pybindings so that the ST-RRT* planner is usable using python. 
I also translated the cpp demo example to a py demo example.
> Add pybindings to ST-RRT* planner

- py-bindings/generate_bindings.py
This allows to use the intermediate solution of anytime planners from
Python.
Example:
pdef.setIntermediateSolutionCallback(
ob.ReportIntermediateSolutionFn(callback))
The current bindings had no ReportIntermediateSolutionFn and thus it was
impossible to use setIntermediateSolutionCallback().
> Add bindings for ReportIntermediateSolutionFn

- src/ompl/geometric/PathGeometric.h
- src/ompl/geometric/src/PathGeometric.cpp
Fixes #1026. Special case for two state case to validate motion, as it won't be checked otherwise.
> Add a special case to checkAndRepair for the two state case

- CMakeLists.txt
- src/ompl/CMakeLists.txt
This allows use of config mode in boost to find it. Regardless of whether boost is found via config or module, the alias targets can, and are preferred, to be used in CMake. 
Reference: https://cmake.org/cmake/help/latest/module/FindBoost.html#boost-cmake
Relates to https://github.com/ompl/ompl/issues/1065
> CMake: Switch to exported namespace targets and prefer config mode

- src/ompl/geometric/planners/informedtrees/bitstar/src/ImplicitGraph.cpp
This hopefully fixes #949.
The errors reported in #949 suggest that the start and goal of a trivial solution (direct start to goal connection) are sometimes pruned. If there are multiple goals and if the heuristic is perfect for a trivial solution (e.g., Euclidean distance heuristic for path length objective in an environment that allows for the trivial solution), then the current code will indeed prune the start and goal. The proposed change directly prevents this by checking the cost of the goal and by adding previously pruned starts back to the samples if necessary.
> Only prune goal in BIT* if it is not part of the current best solution

- src/ompl/base/spaces/DubinsStateSpace.h
- src/ompl/base/spaces/src/DubinsStateSpace.cpp
**Problem Description**
Currently, the Dubins distance computation is done by going through all six path types exhaustively. This is quite inefficient for applications such as sampling-based planners, as the Dubins distance need to be computed many times repeatedly.
It has been proposed by Shkel(2001) that certain Dubins path types can be excluded by looking at the start and end configurations of the path. While the current OMPL implementation of DubinsStateSpace references the paper from Shkel(2001), the implementation goes through every Dubins path type exhaustively. This was discussed previously in an issue: https://github.com/ompl/ompl/issues/1014 with @zkingston and @mamoll 
**Proposed Solution**
The proposed solution is to implement the Dubins Set Classification theme in the …
> Use of Dubins Set Classification for faster distance computations in DubinsStateSpace

- CMakeLists.txt
The latest Eigen3 version 3.4.90 does not define `EIGEN3_INCLUDE_DIR` but embeds everything in an imported target `Eigen3::Eigen`.
> fix: EIGEN3_INCLUDE_DIR is not defined when Eigen3 is installed from source code.

- demos/constraint/ConstrainedPlanningCommon.py
I was experimenting with the demos and fixed a couple of small issues:
(1) Non-simplified path output `.txt` file was the default `str()` signature for the `printAsMatrix` function. Fixed by adding parens.
(2) The following error occurs when running `python demos/constraint/ConstrainedPlanningSphere.py --space AT --bias`:
```
Traceback (most recent call last):
File "demos/constraint/ConstrainedPlanningSphere.py", line 160, in <module>
spherePlanning(parser.parse_args())
File "demos/constraint/ConstrainedPlanningSphere.py", line 127, in spherePlanning
cp = ConstrainedProblem(options.space, rvss, constraint, options)
File "/home/seiji/Research/bimanual-ggcs-analytic-ik/ompl/demos/constraint/ConstrainedPlanningCommon.py", line 176, in __init__
self.css.setBiasFunction(lambda c, …
```
> Fixing missing parens on trajectory output and error from --bias flag in constrained motion planning demos.

- src/ompl/base/samplers/informed/src/RejectionInfSampler.cpp
The rejection sampler currently uses the default state sampler of the state space as base sampler even if the user provided the space with a custom sampler via `StateSpace::setStateSamplerAllocator`. I think it would be more intuitive for the rejection sampler to only fall back to the default state sampler if the user didn't provide a custom one. This would also make it easier to get BIT* et al. to use a custom (uninformed) sampler. Does anyone have any concerns with the proposed change? @gammell?
> Allow allocating custom state sampler in rejection sampler

- CMakeModules/Findcastxml.cmake
- py-bindings/generate_bindings.py
- py-bindings/ompl_py_tools.h
WIP PR for Python bindings on arm64/aarch64 platforms, primarily addressing issues M1 Mac users have had with compiling the Python bindings. I have gotten the bindings to generate and compile on an M1 Mac Mini with some changes to:
- CastXML invocation, to include the default system includes that are missing. This uses the default CastXML available from homebrew.
- Remove Eigen vectorization in the binding generation (not during the actual compilation) to deal with some issues with Neon intrinsics.
- Variety of changes to the bindings to handle platform differences with strings and declarations.
- A mysterious load-bearing include in `ompl_py_tools.h` that otherwise results in a compilation error in CastXML with including `boost/python.hpp` - there probably is some include order …
> Python bindings for ARM and M1 Mac

- .github/workflows/before_all.sh
- .github/workflows/before_build.sh
- .github/workflows/wheels.yaml
- CMakeLists.txt
- CMakeModules/PythonBindingsUtils.cmake
- py-bindings/ompl/base/__init__.py
- py-bindings/pyproject.toml
- py-bindings/setup.py
This PR adds support for building Python wheels for the OMPL package, along with Github CI workflows to do so automatically. The result is that users can install the OMPL Python bindings, with precompiled OMPL shared libraries and all dependencies, like this:
`pip install https://github.com/ompl/ompl/releases/download/prerelease/ompl-1.6.0-cp310-cp310-manylinux_2_28_x86_64.whl`
Along with just about any CPython version [from the cibuildwheel table](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip), supported build targets are:
- Linux x86_64 (via `manylinux_2_28_x86_64`)
- MacOS (both `x86_64` and `arm64`)
This is done using the [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) package to automate building for various operating systems, CPU architectures, and …
> Add support for building Python wheels for Linux & MacOS

- src/ompl/multilevel/datastructures/BundleSpaceSequenceImpl.h
The current implementation of the multilevel planner's solve function terminates as soon as a valid path is found, rendering the user-defined termination parameter ineffective in many scenarios. For instance, when attempting to optimize a solution for a specific duration using the timedPlannerTerminationCondition, the planner terminates prematurely upon finding an initial solution.
To address this issue, the proposed pull request introduces a modification to the termination condition logic. The existing implementation uses an 'or' condition, causing the planner to terminate if either a valid path is found or the user-defined termination parameter is satisfied. The proposed fix adjusts this logic to use an 'and' condition, ensuring that the planner will only terminate when both conditions …
> Fix termination before planner termination condition is met.

- src/ompl/geometric/planners/est/EST.h
Fix a bug I introduced 7 years ago (!).
> fix default value for goal bias fraction in EST planner

- install-ompl-ubuntu.sh.in
Noticed a minor typo in the bash script that triggers an unnecessary error message when installing OMPL.app due to missing space in the if statement.
``` diff
- if [ -z $APP]; then
+ if [ -z $APP ]; then
```
This change is minimal and does not affect the logic of the script. It purely enhances the script cleanliness and prevents misleading error messages during execution.
> Fix syntax error to avoid unnecessary error message in bash script

- .github/workflows/before_build.sh
- .github/workflows/wheels.yaml
- py-bindings/generate_bindings.py
I found a bug wherein, due to `numpy` not being installed correctly before building Boost in the Python wheel CI, `libboost_numpy` would not be built, and so part of the binding generator would silently fail, leading to some components - notably, the constrained planning modules - being missing from the pre-built wheels.
Note that the pip install seems to be necessary; the system-package install (for Linux, at least) places `numpy` in a location that Boost's build does not find.
This PR also adds some output to prevent silent failures like this from going unnoticed in the future and updates the versions of other CI actions used in building Python wheels, in compliance with the warning output visible on the last few runs of the wheel action.
- **Install numpy before building Boost in CI** …
> Fix Python wheels missing constrained planning components

- .github/workflows/wheels.yaml
Unfortunately, the docs I followed in #1160 didn't align with the OMPL Github Actions setup - specifically, the `matrix.runs_on` variable, intended to give each platform's artifact a unique name, was unset. This PR does what #1160 was supposed to do, using the correct platform variables, as well as enabling manual triggering of the wheel build action. I've tested it on my fork, and all builds succeed.
- **fix(CI): Used wrong variable to set unique name for upload artifacts in #1160**
- **feat(CI): Allow manual dispatch of wheel build action**
> Fix CI artifact upload naming, take 2

- .github/workflows/build.yml
Ubuntu 24.04 is now offered as a runner in beta (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). As such, we should test the OMPL build against it. Once it's out of beta, there's another chore to update the wheel building workflow to use Ubuntu 24 instead of 22.
> chore: Add Ubuntu 24.04 to the list of OS versions tested in CI

- demos/multilevel/MultiLevelPlanningKinematicChain.cpp
- src/ompl/geometric/planners/xxl/src/XXL.cpp
Fixes these clang warnings:
```
ompl/geometric/planners/xxl/src/XXL.cpp:356:26: error: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
ompl/demos/multilevel/MultiLevelPlanningKinematicChain.cpp:68:22: error: comparison of integers of different signs: 'value_type' (aka 'int') and 'const unsigned int' [-Werror,-Wsign-compare]
```
> fix signedness compare warning (for -Werror build)

- doc/markdown/pathVisualization.md
There was an off-by-one error in the sample matplotlib script for path vizualization that caused this error:
```
$ python3 plot.py 
/home/ryan/Dev/ompl_ws/tutorials/plot.py:6: MatplotlibDeprecationWarning: Calling gca() with keyword arguments was deprecated in Matplotlib 3.4. Starting two minor releases later, gca() will take no keyword arguments. The gca() function should only be used to get the current axes, or if no axes exist, create new axes with default keyword arguments. To create a new axes with non-default arguments, use plt.axes() or plt.subplot().
ax = fig.gca(projection='3d')
Traceback (most recent call last):
File "/home/ryan/Dev/ompl_ws/tutorials/plot.py", line 7, in <module>
ax.plot(data[:,1],data[:,2],data[:,3],'.-')
IndexError: index 3 is out of bounds for axis 1 with …
```
> Fix off-by-one error and deprecated call in python path visualization tutorial

- CMakeLists.txt
- doc/markdown/installation.md
- src/CMakeLists.txt
* Carry includes through target properties
* Attempt to preserve backwards compatability with OMPL_INCLUDE_DIRS
* Document how to use the library through FetchContent (platform-portable)
* Ensure the build interface can include ompl/config.h
This should also make it work in the same way with `add_subdirectory` for those who use git submodules and similar.
* Solves #1174
I'm haven't tested if I handled `OMPL_INCLUDE_DIRS`. Can we set up a test for this somehow? Make sure `config.h` is found!  Of note, the docs say this: `      To support the previous CMake module behavior, the following variables are defined. These are for backwards compatability, but not recommended anymore.` I don't think this is actually true when we install the package. Let's discuss whether we should fix it. 
```bash …
```
> Use target include directories for FetchContent support

- .github/workflows/build.yml
- src/CMakeLists.txt
* The installation path was incorrectly changed and broke users who link to ompl::ompl after find_package. It was changed to support FetchContent.
* This was caused by the accidental change from https://github.com/ompl/ompl/pull/1182/files#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4L15  to https://github.com/ompl/ompl/pull/1182/files#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4R6
* Add CI to enforce the existing export test because the dockerfile is not build in CI
> Hotfix: Cmake installation with version folder

- .github/workflows/before_all.sh
- .github/workflows/before_build.sh
- .github/workflows/wheels.yaml
- CMakeLists.txt
- CMakeModules/Findcastxml.cmake
- py-bindings/pyproject.toml
- py-bindings/setup.py
- src/ompl/tools/config/SelfConfig.h
- Fix numpy at <2.0 because Boost-Python does not support numpy>=2.0 as of Boost-1.86. See this issue; the fix will likely be included in 1.87: https://github.com/boostorg/python/issues/431
- Use the new Github Mac M1 runner when building the arm64 wheel. This makes that target a native build instead of a cross-compile.
- This requires some additional logic to find the system clang++ executable. I don't have a Mac so I can't test a better solution, but it could probably be cleaned up.
- Work around a `error: no member named 'piecewise_construct' in namespace 'std';` error on MacOS by bumping Boost dependency version. See: https://github.com/NREL/OpenStudio/issues/5229
- Fix a CastXML build error complaining about missing the clang resource directory.
- Silence a CMake warning when using …
> Fix various Python wheel generation issues

- tests/base/planner_data.cpp
- tests/control/planner_data.cpp
Fix: https://github.com/conda-forge/ompl-feedstock/issues/43#issuecomment-2502656357
I ran into this issue as well while debugging https://github.com/conda-forge/ompl-feedstock/issues/43, these two tests are storing/loading from the same file when ran in parallel.
> Save test planner data to different files

- src/ompl/util/src/RandomNumbers.cpp
I am a member of Microsoft vcpkg, due to there are new changes merged by microsoft/STL#5105, which revealed a conformance issue in `ompl`. It must add include `<chrono>` to fix this error.
Compiler error with this STL change:
```
D:\b\ompl\src\1.6.0-33eb9d7aae.clean\src\ompl\util\src\RandomNumbers.cpp(58): error C2039: 'system_clock': is not a member of 'std::chrono'
```
> Include `<chrono>` for system_clock

- .github/workflows/build.yml
the version of macos-12 has exceeded the support period on 16 Sep 2024. We proceed by changing the version to the oldest supported version "13 macos Ventura".
> Update macOs version

- src/ompl/base/StateSpace.h
- src/ompl/base/src/StateSpace.cpp
- tests/base/state_spaces.cpp
Not sure if I'm missing something, but shouldn't isMetricSpace() simply check if all components are metric spaces? The current implementation always return true.
> Override isMetricSpace to check if CompoundStateSpace's components are a metric spaces

- CMakeLists.txt
Compiling c++ code with c++17 standard on macos requires boost 1.68 or higher
https://www.boost.org/users/history/version_1_68_0.html
> Update min. required boost

- .github/workflows/wheels.yaml
- py-bindings/setup.py
- Bump `DCMAKE_OSX_DEPLOYMENT_TARGET` to avoid build failure of `Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=14.0' to update minimum supported macOS for this wheel`, introduced in https://github.com/ompl/ompl/commit/fca3d5f70bec3a15f100f40ebe088506360ed25f.
- Remove wheel builds for EOL Python versions and add Python 13.
Successful CI run here: https://github.com/kylc/ompl/actions/runs/13128098253
> Bump MacOS target version + modernize Python targets

- tests/cmake_export/CMakeLists.txt
Specifically, ensures that `CXX_STANDARD=17`. Otherwise, some OMPL headers will fail to build on compilers that use an older C++ standard by default.
Fixes compile errors in test targets on MacOS in CI.
> Fix failing macOS tests by including CompilerSettings in test target.

- .github/workflows/wheels.yaml
This pull request includes an update to the `.github/workflows/wheels.yaml` file to use the latest version of the `cibuildwheel` action.
* [`.github/workflows/wheels.yaml`](diffhunk://#diff-91b9b589616af36da34e6a0314171ea68cc16b399915d9630a20ea04eb8e99f5L39-R39): Updated `cibuildwheel` action from version `v2.22.0` to `v2.23.0`.
support native arm:
> cibuildwheel 2.23.0

- py-bindings/generate_bindings.py
The python bindings for the `ompl::base::Constraint` class were broken for clang++-17 and possibly other compiler versions. This small change fixes them.
> fix for python bindings

- py-bindings/ompl/__init__.py
Fix library import issue when using virtual environments
- Add missing import.
- Add check site package dir exists.
Fixes: https://github.com/ompl/ompl/issues/1253
> Fix dll_loader in py-bindings

- py-bindings/bindings_generator.py.in
- py-bindings/generate_bindings.py
- py-bindings/ompl_py_base.h
- py-bindings/py_std_optional.hpp
- src/ompl/base/spaces/DubinsStateSpace.h
- src/ompl/base/spaces/src/DubinsStateSpace.cpp
- src/ompl/base/spaces/src/VanaOwenStateSpace.cpp
- src/ompl/base/spaces/src/VanaStateSpace.cpp
Provide a binding generator for `std::optional<T>` and change the storage type of the static array of `DubinsPathSegmentType` from c-style arrays to `std::vector`. This is to allow the Python binding generator to generate interfaces for the `DubinsPath` returned by the `getPath` function in the `DubinsStateSpace`.
- Fixes #1259
This change is more intrusive than I would have liked (ideally the C++ code would not need to change to provide bindings). The preferred solution would be to add a generator for c-style arrays of fixed size, however attempts at this were not successful (see below).
Looked into providing bindings for the c-array types directly and also using `std::array<T, N>`. For some reason neither of these approaches was successful. The bindings appear to have been generated by …
> Enable Python bindings for Dubins path segments 

- src/ompl/base/spaces/DubinsStateSpace.h
- src/ompl/base/spaces/src/DubinsStateSpace.cpp
- src/ompl/base/spaces/src/VanaOwenStateSpace.cpp
Provide safe initialisation and no-destruct for `dubinsPath` object with static storage.
- Closes: https://github.com/ompl/ompl/issues/1270
**Edit** Convert to draft as getting a seg fault on release build on Ubuntu 22.04 in docker. No issue on macOS.
> Fix static initialisation / destruction issue for Dubins path types

- src/ompl/base/spaces/OwenStateSpace.h
**Problem Description**
This PR adds getters to conveniently get properties of OwenStateSpace
**Additional Context**
- @mamoll This was needed for porting `terrain-navigation` for the new OwenStateSpace implementation (https://github.com/ethz-asl/terrain-navigation2/pull/3)
> Add getters for OwenStateSpace

- src/ompl/control/StatePropagator.h
- src/ompl/control/SteeredControlSampler.h
Addresses #1212 to allow steering state propagators to be used from Python. See [this branch of my fork](https://github.com/marip8/ompl/tree/patch/pybindings-wheel-1.6.0) for a functional build of the wheels at 1.6.0 with this fix implemented.
> Update `StatePropagator::steer` method to be compatible with Python

- .github/workflows/before_all.sh
The Python bindings fail to compile with `clang>=19`, which was recently bumped in the container image used to build OMPL wheels. I see the issue in CI and locally. My best guess is that it's related to the combination of recent compiler (`clang-19`) + old Eigen (`3.3.4`).
For now, we should just stick to `clang-18` until a better solution is found or the bindings are replaced with nanobind.
Current error: https://github.com/ompl/ompl/actions/runs/15561864951/job/43815998469#step:3:20189
```
In file included from /project/src/ompl/base/objectives/src/ControlDurationObjective.cpp:37:
In file included from /project/src/ompl/base/objectives/ControlDurationObjective.h:40:
In file included from /project/src/ompl/base/OptimizationObjective.h:41:
In file included from …
```
> Force llvm/clang to v18 in CI to avoid compilation error

- src/ompl/base/spaces/src/TrochoidStateSpace.cpp
to resolve -Werror with clang:
```
ompl/src/ompl/base/spaces/src/TrochoidStateSpace.cpp:586:117: error: unused parameter 'wind_ratio' [-Werror,-Wunused-parameter]
586 |     bool isLongPathCase(double x0, double y0, double phi0, double xf, double yf, double phif, double radius, double wind_ratio)
```
> [fix clang -Werror build] do not name unused parameter

- src/ompl/geometric/planners/informedtrees/bitstar/IdGenerator.h
- src/ompl/geometric/planners/informedtrees/bitstar/src/Vertex.cpp
In the current implementation of `BITstar`, the `IdGenerator` class uses a lock to prevent data races. The same task can be accomplished more effectively with atomic variables, leading to cleaner code and a slight performance boost.
Please review my changes and provide any feedback. I am willing to make further adjustments or conduct additional testing if required.
Thank you for your time and consideration.
reference: https://en.cppreference.com/w/cpp/atomic/atomic/operator_arith
> BITstar: use atomic variable instead of lock in IdGenerator
